name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com
# dart create -t server-shelf server
# dart run --enable-vm-service bin/server.dart
environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  args: ^2.0.0

  #SHELF AND ROUTERS
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_multipart: ^1.0.0
  shelf_hotreload: ^1.3.0

  #DB HELPERS
  mysql1: ^0.20.0

  #PATH MANAGERS
  path: 
dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
